# Generated by Django 5.1.6 on 2025-03-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user_rating_user_ratinganswer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, help_text=' Picture that will be the cover page no webcite', upload_to='medai/main_image', verbose_name='Main photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Product'),
        ),
    ]
