# Generated by Django 5.1.6 on 2025-03-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_options_product_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinganswer',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_answers', to='main.rating', verbose_name='Rating reply'),
        ),
    ]
